name: simple_lan_chat
description: A simple app that allows users on the same LAN to chat through basic UDP packets.

version: '0.9.2'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.3
  connectivity: ^0.4.3
  toast: ^0.1.5
  dynamic_theme: ^1.0.1
  url_launcher: ^5.0.3
  flutter_local_notifications: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true
